### ISSUE TITLE
Need way to manage assets

### ISSUE THREAD

**Issue by davidhemphill** [monarkee/bumble#12]

**Comment by kmcluckie** [comment]
By assets, do you mean images, and the like? Or css/js?

**Comment by davidhemphill** [comment]
Images and other files. :-)

**Comment by kmcluckie** [comment]
I assume you'd want to handle local files and S3 buckets and the like?

I'm a bit of an architecture novice, but I'd like to help if I can, because I think Bumble is pretty damn cool - I love the way it doesn't dictate DB structure.

I'm thinking of a seperate package that could provide the bones of an asset management system. Maybe you can chip in, because, like I said, I'm a bit of a novice.

    interface FileContainerInterface
    {
        public function getFileList($directory);
        public function createFile($path, $contents);
        public function updateFile($path, $contents);
        public function createOrUpdateFile($path, $contents);
        public function getFileContents($path);
        public function deleteFile($path);
    }

This could then be implemented as LocalContainer, S3Container, etc.

We'd also need a FileContainerModel (an Eloquent model for persistence and querying), which would need a DB table with fields:

- name (descriptive name for UI)
- type (LocalContainer, S3Container)
- settings (json settings)

Finally, a FileContainerRepo, or FileContainerService, to find and return FileContainers. It would use FileContainerModels to query the DB but would actually return instances of LocalContainer, FileContainer. Hmm, I might even be able to ditch the FileContainerModel and just use some Fluent in the FileContainerService.

Thoughts? Naming? Validation?
